# Generated by Django 5.1.2 on 2024-10-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.CharField(max_length=500)),
                ('night_of_stay', models.DateField()),
                ('rpg_status', models.CharField(choices=[('1', 'booking'), ('2', 'cancellation')], max_length=1)),
                ('timestamp', models.DateTimeField()),
                ('hotel_id', models.IntegerField()),
            ],
            options={
                'db_table': 'HotelRoom',
            },
        ),
    ]
